# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AUTH_KEY: ${{ secrets.IMPRESSION_SERVICE_AUTH }}
    steps:
    - uses: actions/checkout@v2
    - name: create auth key from secret
      shell: bash
      run: echo "${AUTH_KEY}" > /tmp/auth.json && export GOOGLE_APPLICATION_CREDENTIALS=/tmp/auth.json
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test unittest
      run: |
        python -m unittest discover --start-directory tests/ --pattern test*.py
